-- Seed 8 demo applications matching the Express API data
-- Uses DATEADD for H2 compatibility; works on both H2 and PostgreSQL
INSERT INTO applications (id, prn, first_name, last_name, other_names, email, phone_number, gender, date_of_birth, nationality, district, subcounty, village, program_choice_1, program_choice_2, program_choice_3, study_mode, academic_year, semester, email_verified, status, review_status, submitted_at, reviewed_at, reviewer_notes, uce_result, uace_result, documents, extras, fee_paid, fee_required, fee_currency, created_at, updated_at) VALUES

(1042, 'NEX-26-1042', 'Amina', 'Nabirye', 'Sarah', 'amina.nabirye@example.com', '+256 701 245 801', 'Female', '2005-04-18', 'Ugandan', 'Jinja', 'Buwenge', 'Kakira', 'Bachelor of Computer Science', 'Bachelor of Information Systems', 'Bachelor of Statistics', 'Day', '2026/2027', 'Semester 1', true, 'SUBMITTED', 'Pending review', DATEADD('DAY', -1, CURRENT_TIMESTAMP), NULL, NULL, '{"Mathematics":"A","English":"A","Physics":"B","Chemistry":"B"}', '{"Mathematics":"A","Physics":"B","General Paper":"A","points":18}', '["National ID","UCE Certificate","UACE Certificate","Passport Photo"]', '{"scholarshipRequested":true,"accommodation":true}', 50000, 50000, 'UGX', DATEADD('DAY', -4, CURRENT_TIMESTAMP), DATEADD('DAY', -1, CURRENT_TIMESTAMP)),

(1041, 'NEX-26-1041', 'Daniel', 'Okello', 'Mark', 'daniel.okello@example.com', '+256 772 893 114', 'Male', '2004-11-02', 'Ugandan', 'Gulu', 'Layibi', 'Olya', 'Bachelor of Business Administration', 'Bachelor of Economics', 'Bachelor of Commerce', 'Day', '2026/2027', 'Semester 1', true, 'SUBMITTED', 'Pending review', DATEADD('DAY', -2, CURRENT_TIMESTAMP), NULL, NULL, '{"Mathematics":"B","English":"A","Geography":"A","Entrepreneurship":"A"}', '{"Economics":"A","Entrepreneurship":"B","General Paper":"A","points":15}', '["National ID","UCE Certificate","UACE Certificate"]', '{"scholarshipRequested":false,"accommodation":true}', 50000, 50000, 'UGX', DATEADD('DAY', -5, CURRENT_TIMESTAMP), DATEADD('DAY', -2, CURRENT_TIMESTAMP)),

(1040, 'NEX-26-1040', 'Grace', 'Atim', '', 'grace.atim@example.com', '+256 783 456 220', 'Female', '2005-01-26', 'Ugandan', 'Lira', 'Adyel', 'Ojwina', 'Bachelor of Public Health', 'Bachelor of Biomedical Sciences', 'Bachelor of Nursing Science', 'Day', '2026/2027', 'Semester 1', true, 'ADMITTED', 'Admitted', DATEADD('DAY', -8, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_TIMESTAMP), 'Strong science results and compelling community health statement.', '{"Mathematics":"A","English":"A","Biology":"A","Chemistry":"A"}', '{"Biology":"A","Chemistry":"A","General Paper":"A","points":19}', '["National ID","UCE Certificate","UACE Certificate","Recommendation Letter"]', '{"scholarshipRequested":true,"accommodation":true}', 50000, 50000, 'UGX', DATEADD('DAY', -12, CURRENT_TIMESTAMP), DATEADD('DAY', -3, CURRENT_TIMESTAMP)),

(1039, 'NEX-26-1039', 'Joseph', 'Mugisha', 'Paul', 'joseph.mugisha@example.com', '+256 759 112 883', 'Male', '2004-08-14', 'Ugandan', 'Mbarara', 'Kakoba', 'Ruti', 'Bachelor of Civil Engineering', 'Bachelor of Mechanical Engineering', 'Bachelor of Architecture', 'Day', '2026/2027', 'Semester 1', true, 'WAITLISTED', 'Waitlisted', DATEADD('DAY', -14, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_TIMESTAMP), 'Good profile; held for second-round capacity review.', '{"Mathematics":"A","English":"B","Physics":"A","Chemistry":"B"}', '{"Mathematics":"B","Physics":"B","General Paper":"A","points":14}', '["National ID","UCE Certificate","UACE Certificate"]', '{"scholarshipRequested":false,"accommodation":false}', 50000, 50000, 'UGX', DATEADD('DAY', -17, CURRENT_TIMESTAMP), DATEADD('DAY', -7, CURRENT_TIMESTAMP)),

(1038, 'NEX-26-1038', 'Ruth', 'Nakanwagi', '', 'ruth.nakanwagi@example.com', '+256 704 883 421', 'Female', '2005-06-09', 'Ugandan', 'Wakiso', 'Kira', 'Kiwologoma', 'Bachelor of Laws', 'Bachelor of Arts in Social Sciences', 'Bachelor of Journalism', 'Day', '2026/2027', 'Semester 1', true, 'REJECTED', 'Rejected', DATEADD('DAY', -21, CURRENT_TIMESTAMP), DATEADD('DAY', -11, CURRENT_TIMESTAMP), 'Did not meet the minimum subject requirements for the selected programmes.', '{"Mathematics":"C","English":"B","History":"C","Geography":"C"}', '{"History":"C","General Paper":"C","points":8}', '["National ID","UCE Certificate","UACE Certificate"]', '{"scholarshipRequested":false,"accommodation":false}', 50000, 50000, 'UGX', DATEADD('DAY', -24, CURRENT_TIMESTAMP), DATEADD('DAY', -11, CURRENT_TIMESTAMP)),

(1037, 'NEX-26-1037', 'Brian', 'Ssemanda', 'Ivan', 'brian.ssemanda@example.com', '+256 786 332 109', 'Male', '2005-03-22', 'Ugandan', 'Mukono', 'Goma', 'Seeta', 'Bachelor of Information Technology', 'Bachelor of Computer Science', 'Bachelor of Data Science', 'Weekend', '2026/2027', 'Semester 1', true, 'SUBMITTED', 'Pending review', DATEADD('DAY', -28, CURRENT_TIMESTAMP), NULL, NULL, '{"Mathematics":"A","English":"B","Physics":"B","ICT":"A"}', '{"Mathematics":"B","ICT":"A","General Paper":"A","points":16}', '["National ID","UCE Certificate","UACE Certificate","Portfolio"]', '{"scholarshipRequested":false,"accommodation":false}', 50000, 50000, 'UGX', DATEADD('DAY', -31, CURRENT_TIMESTAMP), DATEADD('DAY', -28, CURRENT_TIMESTAMP)),

(1036, 'NEX-26-1036', 'Martha', 'Akello', 'Jane', 'martha.akello@example.com', '+256 750 901 744', 'Female', '2004-12-30', 'Ugandan', 'Soroti', 'Asuret', 'Arapai', 'Bachelor of Education (Arts)', 'Bachelor of Arts in Development Studies', 'Bachelor of Social Work', 'Day', '2026/2027', 'Semester 1', false, 'DRAFT', 'Not submitted', NULL, NULL, NULL, '{}', '{}', '["Passport Photo"]', '{"scholarshipRequested":false,"accommodation":true}', 0, 50000, 'UGX', DATEADD('DAY', -32, CURRENT_TIMESTAMP), DATEADD('DAY', -32, CURRENT_TIMESTAMP)),

(1035, 'NEX-26-1035', 'Isaac', 'Tumusiime', '', 'isaac.tumusiime@example.com', '+256 778 240 650', 'Male', '2005-09-06', 'Ugandan', 'Kabale', 'Northern', 'Rugarama', 'Bachelor of Tourism Management', 'Bachelor of Business Administration', 'Bachelor of Arts in Economics', 'Day', '2026/2027', 'Semester 1', true, 'SUBMITTED', 'Pending review', DATEADD('DAY', -35, CURRENT_TIMESTAMP), NULL, NULL, '{"Mathematics":"B","English":"A","Geography":"A","History":"B"}', '{"Geography":"A","Economics":"B","General Paper":"A","points":13}', '["National ID","UCE Certificate","UACE Certificate"]', '{"scholarshipRequested":true,"accommodation":true}', 50000, 50000, 'UGX', DATEADD('DAY', -38, CURRENT_TIMESTAMP), DATEADD('DAY', -35, CURRENT_TIMESTAMP));
